### PR TITLE
Numa live migration

### PR DESCRIPTION
**Pull request by gerrykopec**
This backports current nova reviews for numa aware live migration:
https://review.openstack.org/#/q/topic:bp/numa-aware-live-migration

Includes fixes for known issues with numa aware live migration and resource tracker.

### CODE REVIEW

**Comment by dtroyer** [comment]
Thank you Gerry, this is exactly what I was hoping it would be.  Since we are not going to be able to wire up Zuul testing from here as expected I am going to run some Nova tests locally as a sanity check.

* pep8:  One small hit in the last commit, also two hits that also show up in unit tests (see next item)
* py27: 5 failures (tail of log in http://paste.openstack.org/show/749537/).  Two are in tests from subsequent changes that need a small rebase, the other three are warnings about test usage of oslo_db objects.  These may all be just issues with the tests but it seems like we might want to do work-arounds for at least the two 'matchers' failures as they are new tests in these patches.  The other three someone who knows more about Nova can decide.
* functional: Two failed tests (tail of log in http://paste.openstack.org/show/749542/).  The errors in the pythonlogging output for both include nova.compute.manager reporting "Pre live migration failed at host2"

I think all of this (save for the one pep8 thing) are due to bit rot in the upstream reviews.  The functional tests are the only ones that really concern me since I don't know the scope of things there.  They may also be things in the tests that need to be fixed rather than the code itself.

Do we have a plan for pushing the things we have found back upstream?

**Comment by dtroyer** [comment]
One more bit of reference I forgot to put here: the unit test 'matchers' problem is caused by https://review.openstack.org/#/c/641852/ switching to use assertXmlEqual() and that just needs to be reflected in the new tests.

**Comment by gerrykopec** [comment]
Thanks Dean for running the nova tests.  I updated the change and believe I have fixed the pep8 issue and hopefully the py27 failures:
- For the 2 XMLMatches, I've updated the unit test in the upstream commits to follow the change in https://review.openstack.org/#/c/641852/ that you identified.
- For the 3 oslo_db objects, I believe they're the result of me adding the call to instance.refresh() to _post_live_migration() so I've mocked that out in the failing testcases.
Haven't set up the nova tests locally yet so if you can try it out that would be great.

I'm not sure about the functional failures yet.  I'll probably have to set the tests up and debug.

**Comment by dtroyer** [comment]
pep8 and py27 are clean, thanks for the updates.  I still see the same issues in the functional test in nova.tests.functional.notification_sample_tests.test_instance.TestInstanceNotificationSampleWithMultipleComputeOldAttachFlow.test_multiple_compute_actions and nova.tests.functional.notification_sample_tests.test_instance.TestInstanceNotificationSampleWithMultipleCompute.test_multiple_compute_actions, both reporting:

    u'running' != u'pending': path: root.payload.nova_object.data.power_state

(I left out the rest of the data structures)

**Comment by dtroyer** [comment]
A quick update: I have the pep8 and functional tests running under Zuul now, manually via a bit of a hack, but the full logs are available.  First run is in http://logs.openstack.org/30/655930/26/check/stx-nova-stein-pep8/a650a72/ (pep8) and http://logs.openstack.org/30/655930/26/check/stx-nova-stein-functional/ce51681/ (functional).

**Comment by dtroyer** [comment]
I updated https://review.opendev.org/#/c/656065/ again to add the py27 and py36 unit tests, they both pass.  No change in the functional test as one might expect.

**Comment by dtroyer** [comment]
Closing as https://github.com/starlingx-staging/stx-nova/pull/24 was merged with updates

**Pull request closed without merging**
